replicaCount: 1

image:
  repository: 038528481894.dkr.ecr.ap-northeast-1.amazonaws.com/logistics-track
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

resources: {}