name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on:  https://github.com/golangci/golangci-lint:lastest
    steps:
      - run: go mod download
      - run: golangci-lint run -v
  
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.2
      
    - name: Configure AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=ap-northeast-1" >> $GITHUB_ENV
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1.4.0
      with:
        mask-password: true
        registry-type: private
        skip-logout: false

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./app
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/logistics-track:latest

    - name: Build and push Docker image for database
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./app/mysql
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/logistics-database:latest
