name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.2

    - name: Set Image Version
      run: |
        export IMAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.3.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1.4.0
      with:
        mask-password: true
        registry-type: private
        skip-logout: false
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.3.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./app
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/logistics-track:${{ env.IMAGE_VERSION }}
