name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on:  https://github.com/golangci/golangci-lint:lastest
    steps:
      - run: go mod download
      - run: golangci-lint run -v
  
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./app
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/logistics-track:latest

    - name: Build and push Docker image for database
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./app/mysql
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/logistics-database:latest
